### ISSUE TITLE
Build with craftbukkit

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/EnvironmentalEffects#1]
@rourke750 What needs to be changed so the buildserver recognizes the NMS classes? I have it working locally, but the latest build is broken because of those.

**Comment by erocs** [comment]
Different Spigot version. Humbug uses this in it's POM, which looks like
the latest version on the build server.
                <dependency>
                        <groupId>org.spigotmc</groupId>
                        <artifactId>Spigot1.8.7</artifactId>
                        <version>1.8.7</version>
                        <scope>provided</scope>
                </dependency>

**Comment by Maxopoly** [comment]
Yep worked, thanks a lot.
