### ISSUE TITLE
Add option to disable effects for different gamemodes

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/EnvironmentalEffects#8]
Also add a command toggle for op to disable any effects for him.

**Comment by erocs** [comment]
Prefer using new permissions to control these flags.

**Comment by Maxopoly** [comment]
So instead of the command just make a permission to ignore anything and give that to op by default?

**Comment by erocs** [comment]
Yup

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/EnvironmentalEffects/commit/9b99242fb96adc620e5ee87f24ac6f8e6fc7030a
